Repository brightics/studio, pull requests merged in 2019-02, with the labels that each got.

#363 Delete Missing Data
  function/python/brightics/function/transform/meta/delete_missing_data.json
Labels: enhancement

#354 manage common datasets as directories
  function/python/brightics/common/datasets.py
  function/python/brightics/common/test/test_datasets.py
  function/python/brightics/sample_data/iris/iris
Labels: enhancement

#373 Make Query Executor work when there is no matching data.
  function/python/brightics/function/transform/sql/serializer.py
Labels: enhancement

#380 Bug fix:If there is np.nan or float nan in model, it gives an error.
  function/python/brightics/common/json/decoder.py
  function/python/brightics/common/json/encoder.py
Labels: bug

#381 Give an error message if there is a null value in factor column.
  function/python/brightics/function/statistics/anova.py
Labels: bug

#383 Now json also imports tuple, np.array, set, etc.
  function/python/brightics/function/transform/json_extraction.py
Labels: bug, enhancement

#391 Modify 'help' of 'Query Executor'.
  va-server/visual-analytics/public/static/help/python/brightics.function.transform$sql_execute.md
Labels: enhancement

#399 add visible when option
  function/python/brightics/function/recommendation/meta/collaborative_filtering_recommend.json
  function/python/brightics/function/recommendation/meta/collaborative_filtering_train.json
Labels: enhancement
