Repository brightics/studio, pull requests merged in 2019-01, with the labels that each got.

#170 Add function - QueryExecutor, CreateTable
  va-server/visual-analytics/public/css/va/brightics-va.css
  va-server/visual-analytics/public/js/va/brightics-va-core.js
  va-server/visual-analytics/public/js/va/brightics-va-functions.js
Labels: enhancement

#172 statistics - avg to default value
  function/python/brightics/function/statistics/meta/statistic_derivation.json
  function/python/brightics/function/statistics/meta/statistic_summary.json
Labels: enhancement

#177 Brtc issue 174
  function/python/brightics/function/extraction/meta/add_shift.json
  function/python/brightics/function/extraction/shift.py
  function/python/brightics/function/extraction/test/extraction_test.py
Labels: enhancement

#199 binarizer update as development
  function/python/brightics/function/extraction/extraction.py
Labels: enhancement

#215 fix group-by doesn't work in replace_missing_string.
  function/python/brightics/function/manipulation/__init__.py
Labels: bug

#244 move validation module to common
  function/python/brightics/function/classification/decision_tree_classification.py
  function/python/brightics/function/classification/logistic_regression.py
  function/python/brightics/function/classification/svm_classification.py
  function/python/brightics/function/classification/xgb_classification.py
  function/python/brightics/function/clustering/hierarchical_clustering.py
  function/python/brightics/function/clustering/kmeans.py
  function/python/brightics/function/extraction/encoder.py
  function/python/brightics/function/extraction/pca.py
  function/python/brightics/function/io/load.py
  function/python/brightics/function/io/unload.py
  function/python/brightics/function/manipulation/__init__.py
  function/python/brightics/function/manipulation/outlier_detection.py
  function/python/brightics/function/regression/decision_tree_regression.py
  function/python/brightics/function/regression/glm.py
  function/python/brightics/function/regression/xgb_regression.py
  function/python/brightics/function/statistics/cross_table.py
  function/python/brightics/function/statistics/pairplot.py
  function/python/brightics/function/statistics/profile_table.py
  function/python/brightics/function/transform/merge.py
  function/python/brightics/function/transform/missing_data.py
  function/python/brightics/function/transform/reshaping.py
  function/python/brightics/function/transform/sample.py
  function/python/brightics/function/transform/split_data.py
Labels: enhancement

#269 Add unittest_runner module
  function/python/brightics/function/classification/test/classification_test.py
  function/python/brightics/function/clustering/test/clustering_test.py
  function/python/brightics/function/extraction/test/label_encoder_test.py
  function/python/brightics/function/extraction/test/one_hot_encoder_test.py
  function/python/brightics/function/extraction/test/pca_test.py
  function/python/brightics/function/extraction/test/scale_test.py
  function/python/brightics/function/manipulation/__init__.py
  function/python/brightics/function/manipulation/test/manipulation_test.py
  function/python/brightics/function/regression/test/regression_test.py
  function/python/brightics/function/statistics/test/summary_test.py
  function/python/brightics/function/transform/test/transform_test.py
  function/python/brightics/test/brightics_python_runner_test.py
  function/python/brightics/test/data_api_test.py
  function/python/brightics/test/unit_test_runner.py
Labels: enhancement

#271 Update MD Generator for integrating with studio build schedule.
  function/python/brightics/function/util/md_generator.py
Labels: enhancement

#245 add common dataset - iris
  function/python/brightics/common/datasets.py
  function/python/brightics/common/repr.py
  function/python/brightics/common/test/__init__.py
  function/python/brightics/common/test/test_datasets.py
  function/python/brightics/function/classification/test/classification_test.py
  function/python/brightics/function/clustering/test/clustering_test.py
  function/python/brightics/function/extraction/test/extraction_test.py
  function/python/brightics/function/extraction/test/label_encoder_test.py
  function/python/brightics/function/extraction/test/one_hot_encoder_test.py
  function/python/brightics/function/extraction/test/pca_test.py
  function/python/brightics/function/extraction/test/scale_test.py
  function/python/brightics/function/manipulation/test/manipulation_test.py
  function/python/brightics/function/regression/test/regression_test.py
  function/python/brightics/function/test_data.py
  function/python/brightics/sample_data/iris
Labels: enhancement

#299 Add new functions.
  function/python/brightics/function/clustering/__init__.py
  function/python/brightics/function/clustering/gaussian_mixture.py
  function/python/brightics/function/clustering/meta/gaussian_mixture_predict.json
  function/python/brightics/function/clustering/meta/gaussian_mixture_train.json
  function/python/brightics/function/clustering/test/gaussian_mixture.json
  function/python/brightics/function/timeseries/__init__.py
  function/python/brightics/function/timeseries/arima.py
  function/python/brightics/function/timeseries/holt_winters.py
  function/python/brightics/function/timeseries/meta/arima_predict.json
  function/python/brightics/function/timeseries/meta/arima_train.json
  function/python/brightics/function/timeseries/meta/auto_arima_predict.json
  function/python/brightics/function/timeseries/meta/auto_arima_train.json
  function/python/brightics/function/timeseries/meta/holt_winters_predict.json
  function/python/brightics/function/timeseries/meta/holt_winters_train.json
  function/python/brightics/function/timeseries/test/arima.json
  function/python/brightics/function/timeseries/test/holt_winters.json
Labels: enhancement

#326 Modify Naive-Bayes, Holt-Winters, ARIMA, Auto-ARIMA and Statistic summary/derivation.
  function/python/brightics/function/classification/test/Naive-Bayes.json
  function/python/brightics/function/statistics/summary.py
  function/python/brightics/function/timeseries/arima.py
  function/python/brightics/function/timeseries/holt_winters.py
  function/python/brightics/function/timeseries/meta/arima_train.json
  function/python/brightics/function/timeseries/meta/auto_arima_train.json
  function/python/brightics/function/timeseries/meta/holt_winters_train.json
  function/python/brightics/function/timeseries/test/arima.json
  function/python/brightics/function/timeseries/test/holt_winters.json
Labels: enhancement

#335 Delete test models of arima and holt-winters.
  function/python/brightics/function/timeseries/test/arima.json
  function/python/brightics/function/timeseries/test/holt_winters.json
Labels: invalid

#338 Delete test models of tf-idf and latent Dirichlet allocation.
  function/python/brightics/function/textanalytics/test/latent_dirichlet_allocation.json
  function/python/brightics/function/textanalytics/test/tfidf.json
Labels: invalid
