Repository brightics/studio, pull requests merged in 2020-07, with the labels that each got.

#772 Bchart v3.7
  va-server/visual-analytics/app.js
  va-server/visual-analytics/public/css/plugins/brightics/brtc-widgets-all.css
  va-server/visual-analytics/public/css/plugins/brightics/brtc-widgets-all.min.css
  va-server/visual-analytics/views/current-tasks.ejs
  va-server/visual-analytics/views/index.ejs
  va-server/visual-analytics/views/multichart.ejs
  va-server/visual-analytics/views/popupchart.ejs
  va-server/visual-analytics/views/popupimage.ejs
  va-server/visual-analytics/views/popupmodel.ejs
Labels: enhancement

#782 Bump jackson-* from 2.9.* to 2.11.1
  pom.xml
Labels: security

#781 Bump guava from 20.0 to 24.1.1-jre
  pom.xml
Labels: security

#783 Fixed security issues
  pom.xml
Labels: security

#795 Update .travis.yml
  .travis.yml
  docker/docker-deploy.sh
Labels: enhancement

#796 Fixed bug to parquet select columns. And add 'column count' variables
  common/data/src/main/java/com/samsung/sds/brightics/common/data/client/ParquetClient.java
  common/data/src/main/java/com/samsung/sds/brightics/common/data/parquet/reader/info/ParquetInformation.java
  common/data/src/main/java/com/samsung/sds/brightics/common/data/parquet/reader/util/BrighticsParquetUtils.java
  common/data/src/main/java/com/samsung/sds/brightics/common/data/view/ObjectTable.java
Labels: bug, java
